spring:
  datasource:
    url: "jdbc:h2:mem:pokemon"
    driverClassName: org.h2.Driver
    username: "user"
    password: "pass"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: "update"
  h2:
    console:
      enabled: true

server:
  error:
    include-message: always